# Generated by Django 2.1.3 on 2018-11-08 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_deck_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='parentDeck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Deck'),
        ),
    ]
