# Generated by Django 2.1.3 on 2018-11-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_flashcard_parentdeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
