# Generated by Django 2.1.3 on 2018-12-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181128_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='definition',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='term',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
