# Generated by Django 2.1.3 on 2018-12-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181202_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='definition',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='parentdeck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.Deck'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='term',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
